version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    command: sleep infinity
    volumes:
      - ../:/workspace
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
